# Generated by Django 5.2.1 on 2025-12-03 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontest', '0002_add_disqualified_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkontestrelation',
            name='disqualified_reason',
        ),
    ]
